sude: required
services:
    - docker

before_install:
    - docker build -t kamranmirzeyev/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kamranmirzeyev/react-test npm test

after_success:
    - docker build -t kamranmirzeyev/multi-client ./client
    - docker build -t kamranmirzeyev/multi-nginx ./nginx
    - docker build -t kamranmirzeyev/multi-server ./server
    - docker build -t kamranmirzeyev/multi-worker ./worker

   #push docker hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kamran1/multi-client
    - docker push kamran1/multi-nginx
    - docker push kamran1/multi-server
    - docker push kamran1/multi-worker
    
language: generic